# Generated by Django 4.2.1 on 2023-05-27 04:12

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remove_article_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='body',
            field=ckeditor.fields.RichTextField(verbose_name='Article content'),
        ),
    ]
